from enum import StrEnum


class DomainError(Exception):
    def __init__(self, error_code: str):
        super().__init__(error_code)


class ErrorCodes(StrEnum):
    INVALID_BUSINESS_TAX_NUMBER = "INVALID_BUSINESS_TAX_NUMBER"

    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_DAY_OF_WEEK = "INVALID_DAY_OF_WEEK"
    INVALID_UUID_VALUE = "INVALID_UUID_VALUE"
    INVALID_WORK_HOURS = "INVALID_WORK_HOURS"
    INVALID_GEO_POINT = "INVALID_GEO_POINT"
    INVALID_INVENTORY_TYPE = "INVALID_INVENTORY_TYPE"

    INVALID_ORDER_STATUS_TRANSITION = "INVALID_ORDER_STATUS_TRANSITION"
    INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT"
    INVALID_OTP_FORMAT = "INVALID_OTP_FORMAT"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
