"""Initialization

Revision ID: 50f7c216b23b
Revises: 
Create Date: 2026-02-27 21:19:02.419762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f7c216b23b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BANNED', 'DELETING', name='accountstatus'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'CUSTOMER', 'COURIER', 'BUSINESS', name='actortype'), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTER_EMAIL_CONFIRM', name='otppurposetype'), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resend_window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'actor_type', 'purpose', name='uq_otps_actor-type_purpose'),
    sa.UniqueConstraint('otp_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otps')
    op.drop_table('customers')
    # ### end Alembic commands ###
